# Generated by Django 6.1.1 on 2026-09-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('target_audience', models.JSONField(blank=True, default=list)),
                ('cac_relevant', models.BooleanField(default=False)),
                ('cdsa_relevant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_format', models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=16, null=True)),
                ('information_status', models.CharField(choices=[('NOT_RESEARCHED', 'Not Researched'), ('INFORMATION_NOT_PUBLISHED', 'Information Not Yet Published'), ('PARTIAL_INFORMATION', 'Partial Information'), ('COMPLETE', 'Complete'), ('NEEDS_VERIFICATION', 'Needs Verification')], default='NOT_RESEARCHED', max_length=32)),
                ('verification_status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=32)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='conferences.conference')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('conference', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='conferences.conferenceedition')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=16)),
                ('requested_url', models.URLField()),
                ('raw_payload', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='conferences.conference')),
                ('conference_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='conferences.conferenceedition')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('rate_type', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_prices', to='conferences.conferenceedition')),
            ],
        ),
    ]
